name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Set Build Version
      if: github.event_name != 'pull_request'
      run: echo "BUILD_VERSION=1.1.0-$(date +'%Y%m%d%H%M')-${GITHUB_SHA::7}" >> $GITHUB_ENV
      
    - name: Set PR Build Version
      if: github.event_name == 'pull_request'
      run: echo "BUILD_VERSION=1.1.0-PR-${{ github.event.pull_request.number }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn -B clean verify -Pci-cd
      
    - name: Test with Maven
      run: mvn -B test
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: expresso-artifacts
        path: target/expresso-*.jar 