name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    
    - name: Set Build Version for Branch
      if: github.event_name != 'pull_request'
      run: echo "BUILD_VERSION=${BRANCH_NAME}-SNAPSHOT" >> $GITHUB_ENV
      
    - name: Set PR Build Version
      if: github.event_name == 'pull_request'
      run: echo "BUILD_VERSION=PR${{ github.event.pull_request.number }}-SNAPSHOT" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn -B clean verify -Pci-cd -DskipTests
      
    - name: Test with Maven
      run: mvn -B test
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: expresso-artifacts
        path: target/expresso-*.jar 